export const GET_ALL_CONTRACTS_REQUEST = 'GET_ALL_CONTRACTS_REQUEST'
export const GET_ALL_CONTRACTS_SUCCESS = 'GET_ALL_CONTRACTS_SUCCESS'
export const GET_ALL_CONTRACTS_FAIL = 'GET_ALL_CONTRACTS_FAIL'

export const CREATE_CONTRACTS_REQUEST = 'CREATE_CONTRACTS_REQUEST'
export const CREATE_CONTRACTS_SUCCESS = 'CREATE_CONTRACTS_SUCCESS'
export const CREATE_CONTRACTS_FAIL = 'CREATE_CONTRACTS_FAIL'