export const CREATE_MESSAGE_REQUEST = 'CREATE_MESSAGE_REQUEST'
export const CREATE_MESSAGE_FAIL = 'CREATE_MESSAGE_FAIL'
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS'

export const GET_ALL_MESSAGES_REQUEST = 'GET_ALL_MESSAGES_REQUEST'
export const GET_ALL_MESSAGES_SUCCESS = 'GET_ALL_MESSAGES_SUCCESS'
export const GET_ALL_MESSAGES_FAIL = 'GET_ALL_MESSAGES_FAIL'
