export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST' 
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS' 
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL' 

export const GET_ALL_JOB_REQUEST = 'GET_ALL_JOB_REQUEST' 
export const GET_ALL_JOB_SUCCESS = 'GET_ALL_JOB_SUCCESS' 
export const GET_ALL_JOB_FAIL = 'GET_ALL_JOB_FAIL' 

export const GET_SINGLE_JOB_REQUEST = 'GET_SINGLE_JOB_REQUEST' 
export const GET_SINGLE_JOB_SUCCESS = 'GET_SINGLE_JOB_SUCCESS' 
export const GET_SINGLE_JOB_FAIL = 'GET_SINGLE_JOB_FAIL' 

export const GET_USER_JOBS_REQUEST = 'GET_USER_JOBS_REQUEST' 
export const GET_USER_JOBS_SUCCESS = 'GET_USER_JOBS_SUCCESS' 
export const GET_USER_JOBS_FAIL = 'GET_USER_JOBS_FAIL' 

export const SAVE_JOB_REQUEST = 'SAVE_JOB_REQUEST'
export const SAVE_JOB_SUCCESS = 'SAVE_JOB_SUCCESS'
export const SAVE_JOB_FAIL = 'SAVE_JOB_FAIL'
