export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST' 
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS' 
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL' 

export const GET_ALL_JOB_REQUEST = 'GET_ALL_JOB_REQUEST' 
export const GET_ALL_JOB_SUCCESS = 'GET_ALL_JOB_SUCCESS' 
export const GET_ALL_JOB_FAIL = 'GET_ALL_JOB_FAIL' 

