export const SEARCH_ITEM_REQUEST = 'SEARCH_ITEM_REQUEST'
export const SEARCH_ITEM_SUCCESS = 'SEARCH_ITEM_SUCCESS'
export const SEARCH_ITEM_FAIL = 'SEARCH_ITEM_FAIL'

export const FILTER_BY_CATEGORY_REQUEST = 'FILTER_BY_CATEGORY_REQUEST'
export const FILTER_BY_CATEGORY_SUCCESS = 'FILTER_BY_CATEGORY_SUCCESS'
export const FILTER_BY_CATEGORY_FAIL = 'FILTER_BY_CATEGORY_FAIL'