export const SERVICE_GET_REQUEST = 'SERVICE_GET_REQUEST'
export const SERVICE_GET_SUCSESS = 'SERVICE_GET_SUCCESS'
export const SERVICE_GET_FAIL = 'SERVICE_GET_FAIL'

export const ALL_SERVICE_GET_REQUEST = 'ALL_SERVICE_GET_REQUEST'
export const ALL_SERVICE_GET_SUCSESS = 'ALL_SERVICE_GET_SUCCESS'
export const ALL_SERVICE_GET_FAIL = 'ALL_SERVICE_GET_FAIL'

export const SERVIVE_CREATE_REQUEST = 'SERVIVE_CREATE_REQUEST'
export const SERVIVE_CREATE_SUCCESS = 'SERVIVE_CREATE_SUCCESS'
export const SERVIVE_CREATE_FAIL     = 'SERVIVE_CREATE_FAIL'

export const EDIT_SERVICE_REQUEST = 'EDIT_SERVICE_REQUEST'
export const EDIT_SERVICE_SUCCESS = 'EDIT_SERVICE_SUCCESS'
export const EDIT_SERVICE_FAIL = 'EDIT_SERVICE_FAIL'

