export const SERVICE_GET_REQUEST = 'SERVICE_GET_REQUEST'
export const SERVICE_GET_SUCSESS = 'SERVICE_GET_SUCCESS'
export const SERVICE_GET_FAIL = 'SERVICE_GET_FAIL'

export const ALL_SERVICE_GET_REQUEST = 'ALL_SERVICE_GET_REQUEST'
export const ALL_SERVICE_GET_SUCSESS = 'ALL_SERVICE_GET_SUCCESS'
export const ALL_SERVICE_GET_FAIL = 'ALL_SERVICE_GET_FAIL'